
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/jquery.jqplot.min.css" />
<script>
    $(document).ready(function () {
        var data = [
            ['used', <?php echo round($this->userInfos->space_used_in_bytes/1000000)/1000; ?>],
            ['free', <?php echo $this->offer->size_go - round($this->userInfos->space_used_in_bytes/1000000)/1000; ?>]
        ];

        jQuery.jqplot('chartDiskUsage', [data],
            {
                seriesDefaults: {
// Make this a pie chart.
                    renderer: jQuery.jqplot.PieRenderer,
                    rendererOptions: {
// Put data labels on the pie slices.
// By default, labels show the percentage of the slice.
                        showDataLabels: true
                    }
                },
                legend: { show: true, location: 'e' },
                title: 'Disk Usage'
            }
        );
    });
</script>

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.jqplot.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/shCore.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/shBrushJScript.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/shBrushXml.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jqplot.pieRenderer.min.js"></script>


<?php
echo $this->partial('layout/menuLeftCustomer');
?>
<div class="rightContent">
<?php
echo $this->partial('layout/flashMessage');
?>

<?php
$this->headTitle($this->translate('Account Overview'));
?>

<h1 class="page-header center-text"><?php echo $this->translate('Welcome '.$this->userInfos->first_name.' '.$this->userInfos->last_name) ?> </h1>

<?php echo $this->translate('Actually you have <b>'.$this->userInfos->nbr_of_files.' files</b> stored on your cubbyhole.')?><br/>
<?php echo $this->translate('You used <b>'.(round($this->userInfos->space_used_in_bytes/1000000)/1000).' / '.$this->offer->size_go.' GB</b>.')?><br/>
<br/>
    <div id="chartDiskUsage" style="height: 300px; width: 500px; position: relative; margin-left: auto; margin-right: auto;" class="jqplot-target">
    </div>
</div>