<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CubbyHole');?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><!-- LOGO CUBBYHOLE --> &nbsp; CubbyHole</a>
                </div>
                <div class="collapse navbar-collapse">

                        <?php
                        if($user = $this->identity())
                        {
                            ?>
                        <ul class="nav navbar-nav">
                            <li <?php if($this->activeTab == 'home'){ echo 'class="active"'; } ?>><a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>
                        <ul class="pull-right navbar-text">

                            <?php echo sprintf($this->translate('Welcome %s'),$user->first_name) ?>
                            &nbsp;&nbsp;&nbsp;
                            <a class="navbar-link" href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Logout') ?></a>
                        </ul>
                        <?php
                        }
                        else
                        {
                            ?>
                        <ul class="nav navbar-nav">
                            <li <?php if($this->activeTab == 'login'){ echo 'class="active"'; } ?>><a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Login') ?></a></li>
                            <li <?php if($this->activeTab == 'register'){ echo 'class="active"'; } ?>><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a></li>
                        </ul>
                        <?php
                        }
                        ?>

                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; CubbyHole 2014</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
