<script type="text/javascript">
    $(function () {
        $("[rel='tooltip']").tooltip();
    });
</script>

<div class="menuLeft">
<a rel="tooltip" href="<?php echo $this->url('adminUser'); ?>" data-toggle="tooltip" data-placement="right" title="Stats">
    <i class="icon-chart-line menuLeftIcon"></i></a><br/>
<a rel="tooltip" href="<?php echo $this->url('adminUser'); ?>" data-toggle="tooltip" data-placement="right" title="Manage Customers">
    <i class="icon-users menuLeftIcon"></i></a><br/>
<a rel="tooltip" href="<?php echo $this->url('adminOffer'); ?>" data-toggle="tooltip" data-placement="right" title="Manage Offers">
    <i class="icon-briefcase menuLeftIcon"></i></a><br/>
<a rel="tooltip" href="<?php echo $this->url('adminUser'); ?>" data-toggle="tooltip" data-placement="right" title="Manage Workers">
    <i class="icon-network menuLeftIcon"></i></a><br/>
</div>