<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Cubbyhole')) ?></h1>
    <p><?php echo sprintf($this->translate(' - Upload / Dowload / synchronyze files  from all your mobile and desktop devices. <br/> - Share your files with your familly / friends')); ?></p>
    <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('register'); ?>"><?php echo $this->translate('Subscribe now for free') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Offer 1') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Price : Free <br/>')); ?></p>
                <p><a class="btn btn-success pull-right" href="#"><?php echo $this->translate('See more') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Offer 2') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Price : 1.99$ /month')); ?></p>
                <p><a class="btn btn-success pull-right" href="#"><?php echo $this->translate('See more') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Offer 3') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Price 4.99$ /month')); ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo $this->translate('See more') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
