<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Cubbyhole')) ?></h1>
    <p><?php echo sprintf($this->translate(' - Upload / Dowload / synchronyze files  from all your mobile and desktop devices. <br/> - Share your files with your familly / friends')); ?></p>
    <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('register'); ?>"><?php echo $this->translate('Subscribe now for free') ?> &raquo;</a></p>
</div>

<div class="row">
    <?php
    foreach($this->offers as $row) {
        //var_dump($row);
    ?>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate($row->title); ?></h3>
                </div>
                <div class="panel-body">
                    <p><?php echo sprintf($this->translate('Price : '.$row->month_price.'€/month <br/>')); ?></p>
                    <p><?php echo sprintf($this->translate('Space : '.$row->size_go.' GB <br/>')); ?></p>
                    <p><?php echo sprintf($this->translate($row->short_description)); ?></p>
                    <p><a class="btn btn-success pull-right" href="<?php echo $this->url('offer').$row->id; ?>"><?php echo $this->translate('See more') ?> &raquo;</a></p>
                </div>
            </div>
        </div>

        <?php
    }
    ?>
</div>
