<h1 class="page-header center-text"><?php echo $this->translate('Login'); ?></h1>

<?php
echo $this->partial('layout/flashMessage');
?>

<div class="form-container">

<?php
$this->headTitle($this->translate('Login'));
$this->form->setAttribute('action',$this->url('login'));
$this->form->setAttribute('class','form-horizontal');
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo '<div class="input-row">'.$this->formRow($this->form->get('email')).'</div>';
echo '<div class="input-row">'.$this->formRow($this->form->get('password')).'</div>';
echo '<div>'.$this->formSubmit($this->form->get('submit')).'</div>';
echo $this->form()->closeTag();
?>
</div>
<br/>
<div style="text-align:center;">
<b><a href="<?php echo $this->url('register'); ?>"><?php echo $this->translate('No account? subscribe here!') ?></a></b>
</div>